interface teclas {
    displayName: string,
    idArticulo: number,
    color: number
  }
  
export const tecladoVacio: teclas[] = [
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1},
    {  displayName: "", idArticulo: -1, color: 1}
]